# Latest stable Python 3 on Debian Slim image
FROM python:3.9-slim-buster AS standards-validation

ENV NVM_DIR="/usr/local/nvm" \
    PATH=$PATH:/root/.nvm \
    NVM_VERSION=14

# NVM depends on bash
SHELL ["/bin/bash", "-c"]

# Install required tools and packages
RUN : \
 && set -exuo pipefail \
 && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
 && mkdir -p $NVM_DIR \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
        curl \
        build-essential \
        ca-certificates \
        libssl-dev \
        git \
 && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash \
 && apt-get clean \
 && :

# Install dependencies for tools
WORKDIR /src
COPY pyproject.toml /src/

# NVM is super verbose bash so disabling -x for it
RUN : \
 && echo $NVM_VERSION > /src/.nvmrc \
 && source $NVM_DIR/nvm.sh --no-use \
 && set -exuo pipefail \
 && set +x && nvm install && set -x \
 && pip install poetry pre-commit \
 && poetry install \
 && :

# Install pre-commit hooks
COPY .pre-commit-config.yaml /src/
RUN : \
  && git init \
  && pre-commit install --install-hooks \
  && :

# Run validation
COPY . /src/

RUN : \
 && source $NVM_DIR/nvm.sh \
 && set -exuo pipefail \
 && pre-commit run --all-files \
 && :
